name: Build PowerToys Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Install WiX Toolset
      run: |
        curl -LO https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe
        .\wix314.exe /install /quiet
        curl -LO https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip
        7z x wix314-binaries.zip wix.targets -o"C:\Program Files (x86)\WiX Toolset v3.14"
        
    - name: Restore NuGet packages for PowerToys
      run: nuget restore PowerToys.sln

    - name: Build PowerToys Solution
      run: |
        msbuild PowerToys.sln -p:Platform=x64 -p:Configuration=Release -p:TreatWarningsAsErrors=false
        
    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: PowerToys-Installer
        path: x64\Release\
